import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import Navbar from './/components/navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="container-fluid">
            <div className="row flex-xl-nowrap">
                <div className="col-3"></div>
                <main className="col-6 py-md-3 pl-md-5 bd-content">
                    {children}
                </main>
                <div className="col-3"></div>
            </div>

        </div>
      </body>
    </html>




  );
}
